#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        default_batch_fetch_size: 1000
#    database-platform: org.hibernate.dialect.H2Dialect
#    open-in-view: false
#
#  datasource:
#    url: jdbc:h2:tcp://localhost:9092/~/shop
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

# ----